### ISSUE TITLE
Execution of an "Direct Mail: Create Mail from Draft (direct_mail)" scheduler task with cli cronjob fails.

### ISSUE THREAD

**Issue by Patta** [kartolo/direct_mail#401]
TYPO3 11.5.26
direct_mail 9.2.2
PHP 7.4.33

Execution of an "Direct Mail: Create Mail from Draft (direct_mail)" scheduler task with cli cronjob fails.

Cron <user> (typo3_11.5_stage/vendor/bin/typo3cms scheduler:run)  > /dev/null

                                                                               
```
  [ TypeError ]                                                                
  Typed property TYPO3\CMS\Backend\Template\ModuleTemplate::$request must be   
  an instance of Psr\Http\Message\ServerRequestInterface, null used            
                                                                               
```

**Comment by Patta** [comment]
Tested again with:
TYPO3 11.5.28
direct_mail 9.5.0
PHP 8.1.20

Execution of an "Direct Mail: Create Mail from Draft (direct_mail)" scheduler task with cli cronjob failed again, but with different warnings.

```
Mon, 26 Jun 2023 11:50:01 +0200 [WARNING] request="07f96b42025e5" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (BE): PHP Warning: Undefined global variable $TYPO3_REQUEST in /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-backend/Classes/Template/ModuleTemplate.php line 252 

Mon, 26 Jun 2023 11:50:01 +0200 [ERROR] request="07f96b42025e5" component="TYPO3.CMS.Scheduler.Task.AbstractTask": Task failed to execute successfully. Class: TYPO3\CMS\Scheduler\Task\AbstractTask, UID: 104- TypeError: Cannot assign null to property TYPO3\CMS\Backend\Template\ModuleTemplate::$request of type Psr\Http\Message\ServerRequestInterface, in file /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-backend/Classes/Template/ModuleTemplate.php:252 - {"class":"TYPO3\\CMS\\Scheduler\\Task\\AbstractTask","uid":104,"exception":"TypeError: Cannot assign null to property TYPO3\\CMS\\Backend\\Template\\ModuleTemplate::$request of type Psr\\Http\\Message\\ServerRequestInterface in /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-backend/Classes/Template/ModuleTemplate.php:252\nStack trace:\n#0 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php(3249): TYPO3\\CMS\\Backend\\Template\\ModuleTemplate->__construct()\n#1 /var/www/vhosts/REMOVED/typo3_11.5_prod/var/cache/code/di/DependencyInjectionContainer_0edfcc47e58215d3e8dcc41c201327b9eb82c315.php(10415): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::makeInstanceForDi()\n#2 /var/www/vhosts/REMOVED/typo3_11.5_prod/var/cache/code/di/DependencyInjectionContainer_0edfcc47e58215d3e8dcc41c201327b9eb82c315.php(10418): DependencyInjectionContainer_0edfcc47e58215d3e8dcc41c201327b9eb82c315->{closure}()\n#3 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/symfony/dependency-injection/Container.php(240): DependencyInjectionContainer_0edfcc47e58215d3e8dcc41c201327b9eb82c315->getModuleTemplateService()\n#4 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/symfony/dependency-injection/Container.php(220): Symfony\\Component\\DependencyInjection\\Container->make()\n#5 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php(3213): Symfony\\Component\\DependencyInjection\\Container->get()\n#6 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/directmailteam/direct-mail/Classes/Module/MainController.php(81): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::makeInstance()\n#7 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php(3217): DirectMailTeam\\DirectMail\\Module\\MainController->__construct()\n#8 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/directmailteam/direct-mail/Classes/Scheduler/MailFromDraft.php(68): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::makeInstance()\n#9 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-scheduler/Classes/Scheduler.php(192): DirectMailTeam\\DirectMail\\Scheduler\\MailFromDraft->execute()\n#10 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-scheduler/Classes/Command/SchedulerCommand.php(255): TYPO3\\CMS\\Scheduler\\Scheduler->executeTask()\n#11 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-scheduler/Classes/Command/SchedulerCommand.php(194): TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand->executeOrStopTask()\n#12 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-scheduler/Classes/Command/SchedulerCommand.php(120): TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand->loopTasks()\n#13 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/symfony/console/Command/Command.php(298): TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand->execute()\n#14 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/symfony/console/Application.php(1058): Symfony\\Component\\Console\\Command\\Command->run()\n#15 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()\n#16 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()\n#17 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-core/Classes/Console/CommandApplication.php(114): Symfony\\Component\\Console\\Application->run()\n#18 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-cli/typo3(23): TYPO3\\CMS\\Core\\Console\\CommandApplication->run()\n#19 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-cli/typo3(24): {closure}()\n#20 /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/bin/typo3(120): include('...')\n#21 {main}"}

Mon, 26 Jun 2023 11:50:01 +0200 [CRITICAL] request="07f96b42025e5" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (CLI: BE): TypeError, code #0, file /var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-backend/Classes/Template/ModuleTemplate.php, line 252: Cannot assign null to property TYPO3\CMS\Backend\Template\ModuleTemplate::$request of type Psr\Http\Message\ServerRequestInterface - {"mode":"CLI","application_mode":"BE","exception_class":"TypeError","exception_code":0,"file":"/var/www/vhosts/REMOVED/typo3_11.5_prod/vendor/typo3/cms-backend/Classes/Template/ModuleTemplate.php","line":252,"message":"Cannot assign null to property TYPO3\\CMS\\Backend\\Template\\ModuleTemplate::$request of type Psr\\Http\\Message\\ServerRequestInterface","request_url":"http:///typo3_11.5_prod/vendor/bin/typo3","exception":null}
```

**Comment by Patta** [comment]
Tested again with:
TYPO3 12.4.22
PHP 8.2.24
direct_mail 12.x https://github.com/kartolo/direct_mail/commit/500a858bd15c1c97300a35f1fa3c793db6c6c902

Execution of an "Direct Mail: Create Mail from Draft (direct_mail)" scheduler task with cli cronjob failed again, but with different warnings.

```
Tue, 29 Oct 2024 11:00:01 +0100 [WARNING] request="c5afccc050859" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (BE): PHP Warning: Undefined array key "HTTP_HOST" in /var/www/html/vendor/directmailteam/direct-mail/Classes/DirectMailUtility.php line 304 
Tue, 29 Oct 2024 11:00:01 +0100 [ERROR] request="c5afccc050859" component="TYPO3.CMS.Scheduler.Scheduler": Task failed to execute successfully. Class: DirectMailTeam\DirectMail\Scheduler\MailFromDraft, UID: 104, Code: 0, "Class "DirectMailTeam\DirectMail\SiteFinder" not found" in /var/www/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php at line 2985- Error: Class "DirectMailTeam\DirectMail\SiteFinder" not found, in file /var/www/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php:2985 - {"taskClass":"DirectMailTeam\\DirectMail\\Scheduler\\MailFromDraft","taskId":104,"exception":"Error: Class \"DirectMailTeam\\DirectMail\\SiteFinder\" not found in /var/www/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php:2985\nStack trace:\n#0 /var/www/html/vendor/directmailteam/direct-mail/Classes/DirectMailUtility.php(306): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::makeInstance('DirectMailTeam\\\\...')\n#1 /var/www/html/vendor/directmailteam/direct-mail/Classes/DirectMailUtility.php(123): DirectMailTeam\\DirectMail\\DirectMailUtility::getFullUrlsForDirectMailRecord(Array)\n#2 /var/www/html/vendor/directmailteam/direct-mail/Classes/Scheduler/MailFromDraft.php(105): DirectMailTeam\\DirectMail\\DirectMailUtility::fetchUrlContentsForDirectMailRecord(Array, Array, true)\n#3 /var/www/html/vendor/typo3/cms-scheduler/Classes/Scheduler.php(175): DirectMailTeam\\DirectMail\\Scheduler\\MailFromDraft->execute()\n#4 /var/www/html/vendor/typo3/cms-scheduler/Classes/Command/SchedulerCommand.php(241): TYPO3\\CMS\\Scheduler\\Scheduler->executeTask(Object(DirectMailTeam\\DirectMail\\Scheduler\\MailFromDraft))\n#5 /var/www/html/vendor/typo3/cms-scheduler/Classes/Command/SchedulerCommand.php(182): TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand->executeOrStopTask(Object(DirectMailTeam\\DirectMail\\Scheduler\\MailFromDraft))\n#6 /var/www/html/vendor/typo3/cms-scheduler/Classes/Command/SchedulerCommand.php(116): TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand->loopTasks()\n#7 /var/www/html/vendor/symfony/console/Command/Command.php(279): TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 /var/www/html/vendor/symfony/console/Application.php(1047): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand(Object(TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 /var/www/html/vendor/typo3/cms-core/Classes/Console/CommandApplication.php(112): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 /var/www/html/vendor/typo3/cms-cli/typo3(23): TYPO3\\CMS\\Core\\Console\\CommandApplication->run()\n#13 /var/www/html/vendor/typo3/cms-cli/typo3(24): {closure}()\n#14 /var/www/html/vendor/bin/typo3(119): include('/var/www/html/v...')\n#15 {main}","exceptionFile":"/var/www/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php","exceptionLine":2985,"code":0,"message":"Class \"DirectMailTeam\\DirectMail\\SiteFinder\" not found"}
Tue, 29 Oct 2024 11:00:01 +0100 [CRITICAL] request="c5afccc050859" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (CLI: BE): Error, code #0, file /var/www/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php, line 2985: Class "DirectMailTeam\DirectMail\SiteFinder" not found- Error: Class "DirectMailTeam\DirectMail\SiteFinder" not found, in file /var/www/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php:2985 - {"mode":"CLI","application_mode":"BE","exception_class":"Error","exception_code":0,"file":"/var/www/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php","line":2985,"message":"Class \"DirectMailTeam\\DirectMail\\SiteFinder\" not found","request_url":"http:///vendor/bin/typo3","exception":"Error: Class \"DirectMailTeam\\DirectMail\\SiteFinder\" not found in /var/www/html/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php:2985\nStack trace:\n#0 /var/www/html/vendor/directmailteam/direct-mail/Classes/DirectMailUtility.php(306): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::makeInstance('DirectMailTeam\\\\...')\n#1 /var/www/html/vendor/directmailteam/direct-mail/Classes/DirectMailUtility.php(123): DirectMailTeam\\DirectMail\\DirectMailUtility::getFullUrlsForDirectMailRecord(Array)\n#2 /var/www/html/vendor/directmailteam/direct-mail/Classes/Scheduler/MailFromDraft.php(105): DirectMailTeam\\DirectMail\\DirectMailUtility::fetchUrlContentsForDirectMailRecord(Array, Array, true)\n#3 /var/www/html/vendor/typo3/cms-scheduler/Classes/Scheduler.php(175): DirectMailTeam\\DirectMail\\Scheduler\\MailFromDraft->execute()\n#4 /var/www/html/vendor/typo3/cms-scheduler/Classes/Command/SchedulerCommand.php(241): TYPO3\\CMS\\Scheduler\\Scheduler->executeTask(Object(DirectMailTeam\\DirectMail\\Scheduler\\MailFromDraft))\n#5 /var/www/html/vendor/typo3/cms-scheduler/Classes/Command/SchedulerCommand.php(182): TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand->executeOrStopTask(Object(DirectMailTeam\\DirectMail\\Scheduler\\MailFromDraft))\n#6 /var/www/html/vendor/typo3/cms-scheduler/Classes/Command/SchedulerCommand.php(116): TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand->loopTasks()\n#7 /var/www/html/vendor/symfony/console/Command/Command.php(279): TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 /var/www/html/vendor/symfony/console/Application.php(1047): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand(Object(TYPO3\\CMS\\Scheduler\\Command\\SchedulerCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 /var/www/html/vendor/typo3/cms-core/Classes/Console/CommandApplication.php(112): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 /var/www/html/vendor/typo3/cms-cli/typo3(23): TYPO3\\CMS\\Core\\Console\\CommandApplication->run()\n#13 /var/www/html/vendor/typo3/cms-cli/typo3(24): {closure}()\n#14 /var/www/html/vendor/bin/typo3(119): include('/var/www/html/v...')\n#15 {main}"}

```
