### ISSUE TITLE
Undefined array key "transOrigPointerTable" in TempRepository.php line 318

### ISSUE THREAD

**Issue by Patta** [kartolo/direct_mail#413]
TYPO3 11.5.27
PHP 8.1.18
direct_mail 9.3.0

If categories are enabled for tt_address like [here](https://docs.typo3.org/p/directmailteam/direct-mail/9.3/en-us/Configuration/ConfiguringTheUseOfCategories/Index.html) and a category exists, an error occured if an tt_address is opened.
`
An error occurred trying to process items for field "Subscribe to categories" (PHP Warning: Undefined array key "transOrigPointerTable" in /var/www/html/vendor/directmailteam/direct-mail/Classes/Repository/TempRepository.php line 318).
`

An exception is also thrown on step 3 in direct mailer.
`
[CRITICAL] request="a59e383afe1dc" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: BE): TYPO3\CMS\Core\Error\Exception, code #1476107295, file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php, line 137: PHP Warning: Undefined array key "transOrigPointerTable" in /var/www/html/vendor/directmailteam/direct-mail/Classes/Repository/TempRepository.php line 318- Exception: PHP Warning: Undefined array key "transOrigPointerTable" in /var/www/html/vendor/directmailteam/direct-mail/Classes/Repository/TempRepository.php line 318, in file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php:137 - {"mode":"WEB","application_mode":"BE","exception_class":"TYPO3\\CMS\\Core\\Error\\Exception","exception_code":1476107295,"file":"/var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php","line":137,"message":"PHP Warning: Undefined array key \"transOrigPointerTable\" in /var/www/html/vendor/directmailteam/direct-mail/Classes/Repository/TempRepository.php line 318","request_url":"https://REMOVED/typo3/module/DirectMailNavFrame/DirectMail?token=--AnonymizedToken--&id=7439&createMailFrom_UID=8630&fetchAtOnce=1&cmd=info","exception":"TYPO3\\CMS\\Core\\Error\\Exception: PHP Warning: Undefined array key \"transOrigPointerTable\" in /var/www/html/vendor/directmailteam/direct-mail/Classes/Repository/TempRepository.php line 318 in /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php:137\nStack trace:\n#0 /var/www/html/vendor/directmailteam/direct-mail/Classes/Repository/TempRepository.php(318): TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/html/v...', 318)\n#1 /var/www/html/vendor/directmailteam/direct-mail/Classes/Repository/TempRepository.php(294): 
`

**Comment by Patta** [comment]
resolved in [v12.x](https://github.com/kartolo/direct_mail/tree/12.x)
