### ISSUE TITLE
Undefined array key in /Classes/Module/StatisticsController.php

### ISSUE THREAD

**Issue by Patta** [kartolo/direct_mail#417]
TYPO3 11.5.27
PHP 8.1.18
direct_mail 9.4.0

Exception in backend statistics module after click on sent mail.

```
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception

PHP Warning: Undefined array key 15 in /var/www/html/vendor/directmailteam/direct-mail/Classes/Module/StatisticsController.php line 646
in /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php line 137

        }

        $message = self::ERROR_LEVEL_LABELS[$errorLevel] . ': ' . $errorMessage . ' in ' . $errorFile . ' line ' . $errorLine;
        if ($errorLevel & $this->exceptionalErrors) {
            throw new Exception($message, 1476107295);
        }

        $message = $this->getFormattedLogMessage($message);

at TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'Undefined array key 15', '/var/www/html/vendor/directmailteam/direct-mail/Classes/Module/StatisticsController.php', 646)
in /var/www/html/vendor/directmailteam/direct-mail/Classes/Module/StatisticsController.php line 646

                    $label,
                    ($html ? $id : '-'),
                    ($html ? '-' : $id),
                    ($html ? $urlCounter['html'][$id]['counter'] : $urlCounter['plain'][$origId]['counter']),
                    $urlCounter['html'][$id]['counter'],
                    $urlCounter['plain'][$origId]['counter'] ?? 0,
                    $img,
                ];
            }

```

typo3-warning.log

```
Fri, 09 Jun 2023 10:26:04 +0200 [CRITICAL] request="77d0ef1d20c8f" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: BE): TYPO3\CMS\Core\Error\Exception, code #1476107295, file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php, line 137: PHP Warning: Undefined array key 15 in /var/www/html/vendor/directmailteam/direct-mail/Classes/Module/StatisticsController.php line 646- Exception: PHP Warning: Undefined array key 15 in /var/www/html/vendor/directmailteam/direct-mail/Classes/Module/StatisticsController.php line 646, in file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php:137 - {"mode":"WEB","application_mode":"BE","exception_class":"TYPO3\\CMS\\Core\\Error\\Exception","exception_code":1476107295,"file":"/var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php","line":137,"message":"PHP Warning: Undefined array key 15 in /var/www/html/vendor/directmailteam/direct-mail/Classes/Module/StatisticsController.php line 646","request_url":"https://REMOVED/typo3/module/DirectMailNavFrame/Statistics?token=--AnonymizedToken--&id=1234&sys_dmail_uid=1234&cmd=stats&SET%5Bdmail_mode%5D=direct","exception":"TYPO3\\CMS\\Core\\Error\\Exception: PHP Warning: Undefined array key 15 in /var/www/html/vendor/directmailteam/direct-mail/Classes/Module/StatisticsController.php line 646 in /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php:137\nStack trace:\n#0 /var/www/html/vendor/directmailteam/direct-mail/Classes/Module/StatisticsController.php(646): TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/html/v...', 646)\n#1 /var/www/html/vendor/directmailteam/direct-mail/Classes/Module/StatisticsController.php(176): DirectMailTeam\\DirectMail\\Module\\StatisticsController->stats(Array)\n#2 /var/www/html/vendor/directmailteam/direct-mail/Classes/Module/StatisticsController.php(127): DirectMailTeam\\DirectMail\\Module\\StatisticsController->moduleContent()\n#3 /var/www/html/vendor/typo3/cms-backend/Classes/Http/RouteDispatcher.php(91): DirectMailTeam\\DirectMail\\Module\\StatisticsController->indexAction(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#4 /var/www/html/vendor/typo3/cms-backend/Classes/Http/RequestHandler.php(110): TYPO3\\CMS\\Backend\\Http\\RouteDispatcher->dispatch(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#5 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/ResponsePropagation.php(34): TYPO3\\CMS\\Backend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#6 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\ResponsePropagation->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Backend\\Http\\RequestHandler))\n#7 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/SiteResolver.php(69): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#8 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#9 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/AdditionalResponseHeaders.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#10 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\AdditionalResponseHeaders->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#11 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/OutputCompression.php(47): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#12 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#13 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendUserAuthenticator.php(166): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#14 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#15 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendRouteInitialization.php(86): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#16 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#17 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#18 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#19 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/LockedBackendGuard.php(75): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#20 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#21 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/NormalizedParamsAttribute.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#22 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#23 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/VerifyHostHeader.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#24 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\VerifyHostHeader->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#25 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(78): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#26 /var/www/html/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(86): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#27 /var/www/html/vendor/typo3/cms-backend/Classes/Http/Application.php(72): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#28 /var/www/html/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(100): TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#29 /var/www/html/public/typo3/index.php(20): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#30 /var/www/html/public/typo3/index.php(21): {closure}()\n#31 {main}"}
```

**Comment by kartolo** [comment]
PR is merged to master. This will be released soon. Thanks.

/
